### ISSUE TITLE
Can I set a opevm-devnet on amd64 machine?

### ISSUE THREAD

**Issue by yelang376** [availproject/op-evm#243]
If I can, can you tell me the command?
ASSET_ID=$(curl -H "Authorization: token $G_TOKEN" https://api.github.com/repos/availproject/op-evm/releases/tags/v0.1.0 | jq '.assets[] | select(.name == "op-evm-linux-arm64.zip") | .id')
I try to replace "op-evm-linux-arm64.zip" with "op-evm-linux-amd64.zip"
It does not wrok.

**Comment by danielvladco** [comment]
Hello, we do not provide a release for amd64 but it is easy to clone the source code and compile for the desired architecture. To do this follow the steps:

1. Clone the github repo on your local machine
2. Run on the root directory `make build GOOS=linux GOARCH=amd64`
